# Generated by Django 4.2.3 on 2023-07-03 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movies',
            old_name='desc',
            new_name='description',
        ),
    ]
