# Generated by Django 4.2.3 on 2023-07-05 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='favorite',
            name='owner',
            field=models.TextField(default='Hello'),
        ),
    ]
