# Generated by Django 4.2.3 on 2023-07-05 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_alter_favorite_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favorite',
            name='owner',
        ),
    ]
